version: '3.8'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - "8282:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: kamkardan_db_pass_wp
      WORDPRESS_DB_NAME: wordpress
    # platform: linux/amd64

  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kamkardan_db_pass_wp
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: kamkardan_db_pass_wp
    # platform: linux/amd64
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8383:80"
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: kamkardan_db_pass_wp

volumes:
  db_data:
